name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # Use simple_matrix to limit the number of created jobs
      # phpunit.xml.dist has a large number of testsuites, all of which are tested with
      # multiple versions of php + databases in both the modules themselves and other recipes
      # such as recipe-form-building
      simple_matrix: true
      composer_install: true
      # installer contains a sample behat.yml file, though there are no behat tests to run
      endtoend: false
      phpunit: false
      extra_jobs: |
        - endtoend: true
          endtoend_suite: linkfield
          endtoend_config: vendor/silverstripe/linkfield/behat.yml